server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:myapp-test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: http://192.168.0.16:9000
  accessKey: hxl7s3cZznGul93CThXW
  secretKey: usYxxR7oYuxAQr8hKEefC4Kb0wpg20zh2pO8f6zK
  bucketName: minio-bucket
