server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:myapp-test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    debug: true

  data:
    redis:
      host: 192.168.0.16
      port: 6379
      entry-ttl-minutes: 20
      cache-prefix: "spring-boot::"
minio:
  endpoint: http://192.168.0.7:9000
  accessKey: LfFiljALDFjfAC0vLn6q
  secretKey: XoIJz2dd8uL7GFGU1JUBxsMCEflL4yXWMAIhZwsw
  bucketName: minio-bucket
auth:
  refresh-token:
    refresh-exp-hours: 12
  jwt:
    auth-exp-minutes: 120
    secret-key: "JwtSecretKey"
    issuer: "JwtIssuer"

