name: Build Java Project

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/*.jar
      - name: Copy JAR to S3
        run: |
          aws s3 cp $(ls build/libs/*.jar | head -n 1) s3://${{ secrets.S3_BUCKET }}/build/my-app.jar
          VERSION_LABEL=$(date +%Y%m%d%H%M%S)-$(echo $GITHUB_SHA | cut -c1-8)
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.EB_APPLICATION_NAME }} --version-label $VERSION_LABEL --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="build/my-app.jar"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.EB_APPLICATION_NAME }} --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} --version-label $VERSION_LABEL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
